version: '3'
services:
  mysql:
    container_name: geo_entities
    image: mysql:5.7
    command: mysqld --user=root
    restart: always
    environment:
      MYSQL_DATABASE: gis2_novosib
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./doc/gis2_novosib:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
  tomcat:
    container_name: gis_app
    image: tomcat:9.0
    volumes:
      - ./target/org.group.projects.simple.gis-0.0.0-SNAPSHOT.war:/usr/local/tomcat/webapps/simple-gis.war
    ports:
      - "80:8080"      
