version: '2.1'
services:
  mysql:
    container_name: geo_entities
    image: mysql:5.7
    command: mysqld --user=root
    restart: always
    environment:
      MYSQL_DATABASE: gis2_novosib
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./resources/db/gis2_novosib:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10