server:
  port: 8081

  error:
    path: =/error
    whitelabel:
      enabled: false

logging:
  file:
    max-size: 10MB
    path: .

  pattern:
    console: "%clr(%date{HH:mm:ss.SSS}) [%level] %clr(%logger{0}) : %message%n"
    file:    "%clr(%date) [%level] %clr(%logger :) %message%n"

  level:
    root: ERROR
    org.springframework.web: DEBUG
    org.group.projects.simple.gis: INFO

spring:
  output:
    ansi:
      enabled: ALWAYS

  mandatory-file-encoding: UTF-8

  main:
    allow-bean-definition-overriding: true

  datasource:
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql/gis2_novosib?useUnicode=true&characterEncoding=utf-8&characterSetResults=utf-8&useSSL=false
    username: root
    password: root

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
 #       temp:
 #         use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true

  liquibase:
    change-log: classpath:db/db.changelog.xml
    enabled: false

keycloak:
  enabled: false

  realm: simple-gis
  auth-server-url: http://sso:8090/auth
  resource: simple-gis-api
  credentials:
    secret: 97edad04-49ca-4770-8e4a-3bc97c1714ce

  ssl-required: external
  principal-attribute: preferred_username
  use-resource-role-mappings: true
  token-minimum-time-to-live: 30